FROM golang:1.21-alpine AS build

RUN apk add --no-cache build-base

WORKDIR /build
COPY . .
WORKDIR /build/src
RUN go build -o /tmp/mrworker ./main/mrworker.go
RUN go build -buildmode=plugin -o /tmp/wc.so ./mrapps/wc.go

FROM alpine:3.19

WORKDIR /data
COPY --from=build /tmp/mrworker /usr/local/bin/mrworker
COPY --from=build /tmp/wc.so /usr/local/lib/wc.so

ENTRYPOINT ["/usr/local/bin/mrworker"]
CMD ["/usr/local/lib/wc.so"]

